name: Publish GitHub Actions

on:
  push:
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+-?**

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Determine versions
        id: versions
        run: |
          echo "major-version=v$(cat VERSION | cut -f1 -d.)" >> "$GITHUB_OUTPUT"

      - name: Debug versions
        run: |
          echo "${{steps.versions.outputs.major-version}}"
      - run: git tag -f "${{ steps.versions.outputs.major-version }}"
        if: ${{ ! contains(steps.versions.outputs.full-version,'-') }}
      - run: git push -f origin "${{ steps.versions.outputs.major-version }}"
        if: ${{ ! contains(steps.versions.outputs.full-version,'-') }}